name: "Hello world"
version: "1.1.0"
image: "hello_world/image-{arch}-hello-world"
slug: folder
description: >-
  "Long description"
arch:
  - amd64
url: "website with more information about add-on (e.g., a forum thread for support)"